# Generated by Django 3.0.8 on 2020-08-17 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the correct format', regex='^\\+?1?\\d{9,14}$')])),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('first_login', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
